-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 22:30:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zonas` (
  `Nombre` VARCHAR(10) NOT NULL,
  `Viveros_Nombre` VARCHAR(10) NOT NULL,
  `Viveros_Horario` INT NOT NULL,
  `Viveros_Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `Viveros_Nombre`, `Viveros_Horario`, `Viveros_Localización`),
  INDEX `fk_Zonas_Viveros1_idx` (`Viveros_Nombre` ASC, `Viveros_Horario` ASC, `Viveros_Localización` ASC) VISIBLE,
  CONSTRAINT `fk_Zonas_Viveros1`
    FOREIGN KEY (`Viveros_Nombre` , `Viveros_Horario` , `Viveros_Localización`)
    REFERENCES `mydb`.`Viveros` (`Nombre` , `Horario` , `Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calle` (
  `Nombre` VARCHAR(10) NOT NULL,
  `Estado` INT NOT NULL,
  `Zonas_Municipio` VARCHAR(10) NOT NULL,
  `Zonas_Localización` VARCHAR(45) NOT NULL,
  `Zonas_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `Estado`, `Zonas_Municipio`, `Zonas_Localización`, `Zonas_Nombre`),
  INDEX `fk_Calle_Zonas1_idx` (`Zonas_Municipio` ASC, `Zonas_Localización` ASC, `Zonas_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Calle_Zonas1`
    FOREIGN KEY (`Zonas_Municipio` , `Zonas_Localización` , `Zonas_Nombre`)
    REFERENCES `mydb`.`Zonas` (`Municipio` , `Localización` , `Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Construcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Construcciones` (
  `Calle_Nombre` VARCHAR(10) NOT NULL,
  `Calle_Estado` INT NOT NULL,
  `Calle_Zonas_Municipio` VARCHAR(10) NOT NULL,
  `Calle_Zonas_Localización` VARCHAR(45) NOT NULL,
  `Calle_Zonas_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Calle_Nombre`, `Calle_Estado`, `Calle_Zonas_Municipio`, `Calle_Zonas_Localización`, `Calle_Zonas_Nombre`),
  CONSTRAINT `fk_Construcciones_Calle1`
    FOREIGN KEY (`Calle_Nombre` , `Calle_Estado` , `Calle_Zonas_Municipio` , `Calle_Zonas_Localización` , `Calle_Zonas_Nombre`)
    REFERENCES `mydb`.`Calle` (`Nombre` , `Estado` , `Zonas_Municipio` , `Zonas_Localización` , `Zonas_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Unifamiliar` (
  `Espacio` INT NOT NULL,
  `Construcciones_Calle_Nombre` VARCHAR(10) NOT NULL,
  `Construcciones_Calle_Estado` INT NOT NULL,
  `Construcciones_Calle_Zonas_Municipio` VARCHAR(10) NOT NULL,
  `Construcciones_Calle_Zonas_Localización` VARCHAR(45) NOT NULL,
  `Construcciones_Calle_Zonas_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Espacio`, `Construcciones_Calle_Nombre`, `Construcciones_Calle_Estado`, `Construcciones_Calle_Zonas_Municipio`, `Construcciones_Calle_Zonas_Localización`, `Construcciones_Calle_Zonas_Nombre`),
  INDEX `fk_Unifamiliar_Construcciones1_idx` (`Construcciones_Calle_Nombre` ASC, `Construcciones_Calle_Estado` ASC, `Construcciones_Calle_Zonas_Municipio` ASC, `Construcciones_Calle_Zonas_Localización` ASC, `Construcciones_Calle_Zonas_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Unifamiliar_Construcciones1`
    FOREIGN KEY (`Construcciones_Calle_Nombre` , `Construcciones_Calle_Estado` , `Construcciones_Calle_Zonas_Municipio` , `Construcciones_Calle_Zonas_Localización` , `Construcciones_Calle_Zonas_Nombre`)
    REFERENCES `mydb`.`Construcciones` (`Calle_Nombre` , `Calle_Estado` , `Calle_Zonas_Municipio` , `Calle_Zonas_Localización` , `Calle_Zonas_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `Nombre` VARCHAR(10) NOT NULL,
  `DNI` VARCHAR(10) NOT NULL,
  `Unifamiliar_Espacio` INT NOT NULL,
  `Unifamiliar_Construcciones_Calle_Nombre` VARCHAR(10) NOT NULL,
  `Unifamiliar_Construcciones_Calle_Estado` INT NOT NULL,
  `Unifamiliar_Construcciones_Calle_Zonas_Municipio` VARCHAR(10) NOT NULL,
  `Unifamiliar_Construcciones_Calle_Zonas_Localización` VARCHAR(45) NOT NULL,
  `Unifamiliar_Construcciones_Calle_Zonas_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `DNI`, `Unifamiliar_Espacio`, `Unifamiliar_Construcciones_Calle_Nombre`, `Unifamiliar_Construcciones_Calle_Estado`, `Unifamiliar_Construcciones_Calle_Zonas_Municipio`, `Unifamiliar_Construcciones_Calle_Zonas_Localización`, `Unifamiliar_Construcciones_Calle_Zonas_Nombre`),
  INDEX `fk_Persona_Unifamiliar1_idx` (`Unifamiliar_Espacio` ASC, `Unifamiliar_Construcciones_Calle_Nombre` ASC, `Unifamiliar_Construcciones_Calle_Estado` ASC, `Unifamiliar_Construcciones_Calle_Zonas_Municipio` ASC, `Unifamiliar_Construcciones_Calle_Zonas_Localización` ASC, `Unifamiliar_Construcciones_Calle_Zonas_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Persona_Unifamiliar1`
    FOREIGN KEY (`Unifamiliar_Espacio` , `Unifamiliar_Construcciones_Calle_Nombre` , `Unifamiliar_Construcciones_Calle_Estado` , `Unifamiliar_Construcciones_Calle_Zonas_Municipio` , `Unifamiliar_Construcciones_Calle_Zonas_Localización` , `Unifamiliar_Construcciones_Calle_Zonas_Nombre`)
    REFERENCES `mydb`.`Unifamiliar` (`Espacio` , `Construcciones_Calle_Nombre` , `Construcciones_Calle_Estado` , `Construcciones_Calle_Zonas_Municipio` , `Construcciones_Calle_Zonas_Localización` , `Construcciones_Calle_Zonas_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bloque` (
  `Construcciones_Calle_Nombre` VARCHAR(10) NOT NULL,
  `Construcciones_Calle_Estado` INT NOT NULL,
  `Construcciones_Calle_Zonas_Municipio` VARCHAR(10) NOT NULL,
  `Construcciones_Calle_Zonas_Localización` VARCHAR(45) NOT NULL,
  `Construcciones_Calle_Zonas_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Construcciones_Calle_Nombre`, `Construcciones_Calle_Estado`, `Construcciones_Calle_Zonas_Municipio`, `Construcciones_Calle_Zonas_Localización`, `Construcciones_Calle_Zonas_Nombre`),
  CONSTRAINT `fk_Bloque_Construcciones1`
    FOREIGN KEY (`Construcciones_Calle_Nombre` , `Construcciones_Calle_Estado` , `Construcciones_Calle_Zonas_Municipio` , `Construcciones_Calle_Zonas_Localización` , `Construcciones_Calle_Zonas_Nombre`)
    REFERENCES `mydb`.`Construcciones` (`Calle_Nombre` , `Calle_Estado` , `Calle_Zonas_Municipio` , `Calle_Zonas_Localización` , `Calle_Zonas_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Viveros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Viveros` (
  `Nombre` VARCHAR(10) NOT NULL,
  `Horario` INT NOT NULL,
  `Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `Horario`, `Localización`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zonas` (
  `Nombre` VARCHAR(10) NOT NULL,
  `Viveros_Nombre` VARCHAR(10) NOT NULL,
  `Viveros_Horario` INT NOT NULL,
  `Viveros_Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `Viveros_Nombre`, `Viveros_Horario`, `Viveros_Localización`),
  INDEX `fk_Zonas_Viveros1_idx` (`Viveros_Nombre` ASC, `Viveros_Horario` ASC, `Viveros_Localización` ASC) VISIBLE,
  CONSTRAINT `fk_Zonas_Viveros1`
    FOREIGN KEY (`Viveros_Nombre` , `Viveros_Horario` , `Viveros_Localización`)
    REFERENCES `mydb`.`Viveros` (`Nombre` , `Horario` , `Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `Fecha de caducidad` INT NOT NULL,
  `Stock` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Precio` INT NOT NULL,
  `Codigo de barras` VARCHAR(10) NOT NULL,
  `Zonas_Nombre` VARCHAR(10) NOT NULL,
  `Zonas_Viveros_Nombre` VARCHAR(10) NOT NULL,
  `Zonas_Viveros_Horario` INT NOT NULL,
  `Zonas_Viveros_Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Fecha de caducidad`, `Stock`, `Tipo`, `Precio`, `Codigo de barras`, `Zonas_Nombre`, `Zonas_Viveros_Nombre`, `Zonas_Viveros_Horario`, `Zonas_Viveros_Localización`),
  INDEX `fk_Producto_Zonas1_idx` (`Zonas_Nombre` ASC, `Zonas_Viveros_Nombre` ASC, `Zonas_Viveros_Horario` ASC, `Zonas_Viveros_Localización` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Zonas1`
    FOREIGN KEY (`Zonas_Nombre` , `Zonas_Viveros_Nombre` , `Zonas_Viveros_Horario` , `Zonas_Viveros_Localización`)
    REFERENCES `mydb`.`Zonas` (`Nombre` , `Viveros_Nombre` , `Viveros_Horario` , `Viveros_Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `CSS` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Seguridad Social` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `Nómina` INT NOT NULL,
  `Zonas_Nombre` VARCHAR(10) NOT NULL,
  `Zonas_Viveros_Nombre` VARCHAR(10) NOT NULL,
  `Zonas_Viveros_Horario` INT NOT NULL,
  `Zonas_Viveros_Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CSS`, `Nombre`, `Seguridad Social`, `DNI`, `Nómina`, `Zonas_Nombre`, `Zonas_Viveros_Nombre`, `Zonas_Viveros_Horario`, `Zonas_Viveros_Localización`),
  INDEX `fk_Empleado_Zonas1_idx` (`Zonas_Nombre` ASC, `Zonas_Viveros_Nombre` ASC, `Zonas_Viveros_Horario` ASC, `Zonas_Viveros_Localización` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Zonas1`
    FOREIGN KEY (`Zonas_Nombre` , `Zonas_Viveros_Nombre` , `Zonas_Viveros_Horario` , `Zonas_Viveros_Localización`)
    REFERENCES `mydb`.`Zonas` (`Nombre` , `Viveros_Nombre` , `Viveros_Horario` , `Viveros_Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `Fecha` INT NOT NULL,
  `Dirección de envio` VARCHAR(45) NOT NULL,
  `Importe` INT NOT NULL,
  `Empleado_CSS` VARCHAR(10) NOT NULL,
  `Empleado_Nombre` VARCHAR(45) NOT NULL,
  `Empleado_Seguridad Social` VARCHAR(45) NOT NULL,
  `Empleado_DNI` VARCHAR(45) NOT NULL,
  `Empleado_Nómina` INT NOT NULL,
  `Empleado_Zonas_Nombre` VARCHAR(10) NOT NULL,
  `Empleado_Zonas_Viveros_Nombre` VARCHAR(10) NOT NULL,
  `Empleado_Zonas_Viveros_Horario` INT NOT NULL,
  `Empleado_Zonas_Viveros_Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Fecha`, `Importe`, `Dirección de envio`, `Empleado_CSS`, `Empleado_Nombre`, `Empleado_Seguridad Social`, `Empleado_DNI`, `Empleado_Nómina`, `Empleado_Zonas_Nombre`, `Empleado_Zonas_Viveros_Nombre`, `Empleado_Zonas_Viveros_Horario`, `Empleado_Zonas_Viveros_Localización`),
  INDEX `fk_Pedido_Empleado1_idx` (`Empleado_CSS` ASC, `Empleado_Nombre` ASC, `Empleado_Seguridad Social` ASC, `Empleado_DNI` ASC, `Empleado_Nómina` ASC, `Empleado_Zonas_Nombre` ASC, `Empleado_Zonas_Viveros_Nombre` ASC, `Empleado_Zonas_Viveros_Horario` ASC, `Empleado_Zonas_Viveros_Localización` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Empleado1`
    FOREIGN KEY (`Empleado_CSS` , `Empleado_Nombre` , `Empleado_Seguridad Social` , `Empleado_DNI` , `Empleado_Nómina` , `Empleado_Zonas_Nombre` , `Empleado_Zonas_Viveros_Nombre` , `Empleado_Zonas_Viveros_Horario` , `Empleado_Zonas_Viveros_Localización`)
    REFERENCES `mydb`.`Empleado` (`CSS` , `Nombre` , `Seguridad Social` , `DNI` , `Nómina` , `Zonas_Nombre` , `Zonas_Viveros_Nombre` , `Zonas_Viveros_Horario` , `Zonas_Viveros_Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Fidelización` VARCHAR(10) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Fidelización`, `DNI`, `Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso` (
  `Número` INT NOT NULL,
  `Piso` INT NOT NULL,
  `Bloque_Construcciones_Calle_Nombre` VARCHAR(10) NOT NULL,
  `Bloque_Construcciones_Calle_Estado` INT NOT NULL,
  `Bloque_Construcciones_Calle_Zonas_Municipio` VARCHAR(10) NOT NULL,
  `Bloque_Construcciones_Calle_Zonas_Localización` VARCHAR(45) NOT NULL,
  `Bloque_Construcciones_Calle_Zonas_Nombre` VARCHAR(45) NOT NULL,
  `Persona_Nombre` VARCHAR(10) NOT NULL,
  `Persona_DNI` VARCHAR(10) NOT NULL,
  `Persona_Unifamiliar_Espacio` INT NOT NULL,
  `Persona_Unifamiliar_Construcciones_Calle_Nombre` VARCHAR(10) NOT NULL,
  `Persona_Unifamiliar_Construcciones_Calle_Estado` INT NOT NULL,
  `Persona_Unifamiliar_Construcciones_Calle_Zonas_Municipio` VARCHAR(10) NOT NULL,
  `Persona_Unifamiliar_Construcciones_Calle_Zonas_Localización` VARCHAR(45) NOT NULL,
  `Persona_Unifamiliar_Construcciones_Calle_Zonas_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Número`, `Piso`, `Bloque_Construcciones_Calle_Nombre`, `Bloque_Construcciones_Calle_Estado`, `Bloque_Construcciones_Calle_Zonas_Municipio`, `Bloque_Construcciones_Calle_Zonas_Localización`, `Bloque_Construcciones_Calle_Zonas_Nombre`, `Persona_Nombre`, `Persona_DNI`, `Persona_Unifamiliar_Espacio`, `Persona_Unifamiliar_Construcciones_Calle_Nombre`, `Persona_Unifamiliar_Construcciones_Calle_Estado`, `Persona_Unifamiliar_Construcciones_Calle_Zonas_Municipio`, `Persona_Unifamiliar_Construcciones_Calle_Zonas_Localización`, `Persona_Unifamiliar_Construcciones_Calle_Zonas_Nombre`),
  INDEX `fk_Piso_Bloque1_idx` (`Bloque_Construcciones_Calle_Nombre` ASC, `Bloque_Construcciones_Calle_Estado` ASC, `Bloque_Construcciones_Calle_Zonas_Municipio` ASC, `Bloque_Construcciones_Calle_Zonas_Localización` ASC, `Bloque_Construcciones_Calle_Zonas_Nombre` ASC) VISIBLE,
  INDEX `fk_Piso_Persona1_idx` (`Persona_Nombre` ASC, `Persona_DNI` ASC, `Persona_Unifamiliar_Espacio` ASC, `Persona_Unifamiliar_Construcciones_Calle_Nombre` ASC, `Persona_Unifamiliar_Construcciones_Calle_Estado` ASC, `Persona_Unifamiliar_Construcciones_Calle_Zonas_Municipio` ASC, `Persona_Unifamiliar_Construcciones_Calle_Zonas_Localización` ASC, `Persona_Unifamiliar_Construcciones_Calle_Zonas_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Piso_Bloque1`
    FOREIGN KEY (`Bloque_Construcciones_Calle_Nombre` , `Bloque_Construcciones_Calle_Estado` , `Bloque_Construcciones_Calle_Zonas_Municipio` , `Bloque_Construcciones_Calle_Zonas_Localización` , `Bloque_Construcciones_Calle_Zonas_Nombre`)
    REFERENCES `mydb`.`Bloque` (`Construcciones_Calle_Nombre` , `Construcciones_Calle_Estado` , `Construcciones_Calle_Zonas_Municipio` , `Construcciones_Calle_Zonas_Localización` , `Construcciones_Calle_Zonas_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Piso_Persona1`
    FOREIGN KEY (`Persona_Nombre` , `Persona_DNI` , `Persona_Unifamiliar_Espacio` , `Persona_Unifamiliar_Construcciones_Calle_Nombre` , `Persona_Unifamiliar_Construcciones_Calle_Estado` , `Persona_Unifamiliar_Construcciones_Calle_Zonas_Municipio` , `Persona_Unifamiliar_Construcciones_Calle_Zonas_Localización` , `Persona_Unifamiliar_Construcciones_Calle_Zonas_Nombre`)
    REFERENCES `mydb`.`Persona` (`Nombre` , `DNI` , `Unifamiliar_Espacio` , `Unifamiliar_Construcciones_Calle_Nombre` , `Unifamiliar_Construcciones_Calle_Estado` , `Unifamiliar_Construcciones_Calle_Zonas_Municipio` , `Unifamiliar_Construcciones_Calle_Zonas_Localización` , `Unifamiliar_Construcciones_Calle_Zonas_Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
