-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 19:43:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Catastro_Carlos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Catastro_Carlos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Catastro_Carlos` DEFAULT CHARACTER SET utf8 ;
USE `Catastro_Carlos` ;

-- -----------------------------------------------------
-- Table `Catastro_Carlos`.`Zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Catastro_Carlos`.`Zonas` (
  `Municipio` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Localización` VARCHAR(45) NULL,
  PRIMARY KEY (`Municipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Catastro_Carlos`.`Construcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Catastro_Carlos`.`Construcciones` (
  `Nombre` VARCHAR(10) NOT NULL,
  `Estado` INT NOT NULL,
  `Zonas_Municipio` VARCHAR(10) NOT NULL,
  `Calles` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `Zonas_Municipio`, `Calles`),
  INDEX `Municipio_idx` (`Zonas_Municipio` ASC) VISIBLE,
  CONSTRAINT `Municipio`
    FOREIGN KEY (`Zonas_Municipio`)
    REFERENCES `Catastro_Carlos`.`Zonas` (`Municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Catastro_Carlos`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Catastro_Carlos`.`Bloque` (
  `Construcciones_Nombre` VARCHAR(10) NOT NULL,
  `Construcciones_Zonas_Municipio` VARCHAR(10) NOT NULL,
  `Construcciones_Calles` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Construcciones_Nombre`, `Construcciones_Zonas_Municipio`, `Construcciones_Calles`),
  CONSTRAINT `Construcciones`
    FOREIGN KEY (`Construcciones_Nombre` , `Construcciones_Zonas_Municipio` , `Construcciones_Calles`)
    REFERENCES `Catastro_Carlos`.`Construcciones` (`Nombre` , `Zonas_Municipio` , `Calles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Catastro_Carlos`.`Unifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Catastro_Carlos`.`Unifamiliar` (
  `Espacio` INT NOT NULL,
  `Construcciones_Nombre` VARCHAR(10) NOT NULL,
  `Construcciones_Zonas_Municipio` VARCHAR(10) NOT NULL,
  `Construcciones_Calles` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Espacio`, `Construcciones_Nombre`, `Construcciones_Zonas_Municipio`, `Construcciones_Calles`),
  INDEX `fk_Unifamiliar_Construcciones1_idx` (`Construcciones_Nombre` ASC, `Construcciones_Zonas_Municipio` ASC, `Construcciones_Calles` ASC) VISIBLE,
  CONSTRAINT `Construcciones`
    FOREIGN KEY (`Construcciones_Nombre` , `Construcciones_Zonas_Municipio` , `Construcciones_Calles`)
    REFERENCES `Catastro_Carlos`.`Construcciones` (`Nombre` , `Zonas_Municipio` , `Calles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Catastro_Carlos`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Catastro_Carlos`.`Piso` (
  `Número` INT NOT NULL,
  `Planta` INT NOT NULL,
  PRIMARY KEY (`Número`),
  CONSTRAINT `Bloque`
    FOREIGN KEY ()
    REFERENCES `Catastro_Carlos`.`Bloque` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Catastro_Carlos`.`Personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Catastro_Carlos`.`Personas` (
  `DNI` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`),
  CONSTRAINT `Unifamiliar`
    FOREIGN KEY ()
    REFERENCES `Catastro_Carlos`.`Unifamiliar` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Piso`
    FOREIGN KEY ()
    REFERENCES `Catastro_Carlos`.`Piso` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
