-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 21:53:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `Nombre` VARCHAR(10) NOT NULL,
  `DNI` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Nombre`, `DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calle` (
  `Nombre` VARCHAR(10) NOT NULL,
  `Estado` INT NOT NULL,
  PRIMARY KEY (`Nombre`, `Estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zonas` (
  `Nombre` VARCHAR(10) NOT NULL,
  `Viveros_Nombre` VARCHAR(10) NOT NULL,
  `Viveros_Horario` INT NOT NULL,
  `Viveros_Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `Viveros_Nombre`, `Viveros_Horario`, `Viveros_Localización`),
  INDEX `fk_Zonas_Viveros1_idx` (`Viveros_Nombre` ASC, `Viveros_Horario` ASC, `Viveros_Localización` ASC) VISIBLE,
  CONSTRAINT `fk_Zonas_Viveros1`
    FOREIGN KEY (`Viveros_Nombre` , `Viveros_Horario` , `Viveros_Localización`)
    REFERENCES `mydb`.`Viveros` (`Nombre` , `Horario` , `Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Construcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Construcciones` (
  `Calle_Nombre` VARCHAR(10) NOT NULL,
  `Calle_Estado` INT NOT NULL,
  PRIMARY KEY (`Calle_Nombre`, `Calle_Estado`),
  CONSTRAINT `fk_Construcciones_Calle1`
    FOREIGN KEY (`Calle_Nombre` , `Calle_Estado`)
    REFERENCES `mydb`.`Calle` (`Nombre` , `Estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Unifamiliar` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bloque` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Viveros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Viveros` (
  `Nombre` VARCHAR(10) NOT NULL,
  `Horario` INT NOT NULL,
  `Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `Horario`, `Localización`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zonas` (
  `Nombre` VARCHAR(10) NOT NULL,
  `Viveros_Nombre` VARCHAR(10) NOT NULL,
  `Viveros_Horario` INT NOT NULL,
  `Viveros_Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `Viveros_Nombre`, `Viveros_Horario`, `Viveros_Localización`),
  INDEX `fk_Zonas_Viveros1_idx` (`Viveros_Nombre` ASC, `Viveros_Horario` ASC, `Viveros_Localización` ASC) VISIBLE,
  CONSTRAINT `fk_Zonas_Viveros1`
    FOREIGN KEY (`Viveros_Nombre` , `Viveros_Horario` , `Viveros_Localización`)
    REFERENCES `mydb`.`Viveros` (`Nombre` , `Horario` , `Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `Fecha de caducidad` INT NOT NULL,
  `Stock` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Precio` INT NOT NULL,
  `Codigo de barras` VARCHAR(10) NOT NULL,
  `Zonas_Nombre` VARCHAR(10) NOT NULL,
  `Zonas_Viveros_Nombre` VARCHAR(10) NOT NULL,
  `Zonas_Viveros_Horario` INT NOT NULL,
  `Zonas_Viveros_Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Fecha de caducidad`, `Stock`, `Tipo`, `Precio`, `Codigo de barras`, `Zonas_Nombre`, `Zonas_Viveros_Nombre`, `Zonas_Viveros_Horario`, `Zonas_Viveros_Localización`),
  INDEX `fk_Producto_Zonas1_idx` (`Zonas_Nombre` ASC, `Zonas_Viveros_Nombre` ASC, `Zonas_Viveros_Horario` ASC, `Zonas_Viveros_Localización` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Zonas1`
    FOREIGN KEY (`Zonas_Nombre` , `Zonas_Viveros_Nombre` , `Zonas_Viveros_Horario` , `Zonas_Viveros_Localización`)
    REFERENCES `mydb`.`Zonas` (`Nombre` , `Viveros_Nombre` , `Viveros_Horario` , `Viveros_Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `CSS` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Seguridad Social` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `Nómina` INT NOT NULL,
  `Zonas_Nombre` VARCHAR(10) NOT NULL,
  `Zonas_Viveros_Nombre` VARCHAR(10) NOT NULL,
  `Zonas_Viveros_Horario` INT NOT NULL,
  `Zonas_Viveros_Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CSS`, `Nombre`, `Seguridad Social`, `DNI`, `Nómina`, `Zonas_Nombre`, `Zonas_Viveros_Nombre`, `Zonas_Viveros_Horario`, `Zonas_Viveros_Localización`),
  INDEX `fk_Empleado_Zonas1_idx` (`Zonas_Nombre` ASC, `Zonas_Viveros_Nombre` ASC, `Zonas_Viveros_Horario` ASC, `Zonas_Viveros_Localización` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Zonas1`
    FOREIGN KEY (`Zonas_Nombre` , `Zonas_Viveros_Nombre` , `Zonas_Viveros_Horario` , `Zonas_Viveros_Localización`)
    REFERENCES `mydb`.`Zonas` (`Nombre` , `Viveros_Nombre` , `Viveros_Horario` , `Viveros_Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Fidelización` VARCHAR(10) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Fidelización`, `DNI`, `Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `Fecha` INT NOT NULL,
  `Dirección de envio` VARCHAR(45) NOT NULL,
  `Importe` INT NOT NULL,
  `Empleado_CSS` VARCHAR(10) NOT NULL,
  `Empleado_Nombre` VARCHAR(45) NOT NULL,
  `Empleado_Seguridad Social` VARCHAR(45) NOT NULL,
  `Empleado_DNI` VARCHAR(45) NOT NULL,
  `Empleado_Nómina` INT NOT NULL,
  `Empleado_Zonas_Nombre` VARCHAR(10) NOT NULL,
  `Empleado_Zonas_Viveros_Nombre` VARCHAR(10) NOT NULL,
  `Empleado_Zonas_Viveros_Horario` INT NOT NULL,
  `Empleado_Zonas_Viveros_Localización` VARCHAR(45) NOT NULL,
  `Producto_Fecha de caducidad` INT NOT NULL,
  `Producto_Stock` VARCHAR(45) NOT NULL,
  `Producto_Tipo` VARCHAR(45) NOT NULL,
  `Producto_Precio` INT NOT NULL,
  `Producto_Codigo de barras` VARCHAR(10) NOT NULL,
  `Producto_Zonas_Nombre` VARCHAR(10) NOT NULL,
  `Producto_Zonas_Viveros_Nombre` VARCHAR(10) NOT NULL,
  `Producto_Zonas_Viveros_Horario` INT NOT NULL,
  `Producto_Zonas_Viveros_Localización` VARCHAR(45) NOT NULL,
  `Cliente_Fidelización` VARCHAR(10) NOT NULL,
  `Cliente_DNI` VARCHAR(45) NOT NULL,
  `Cliente_Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Fecha`, `Importe`, `Dirección de envio`, `Empleado_CSS`, `Empleado_Nombre`, `Empleado_Seguridad Social`, `Empleado_DNI`, `Empleado_Nómina`, `Empleado_Zonas_Nombre`, `Empleado_Zonas_Viveros_Nombre`, `Empleado_Zonas_Viveros_Horario`, `Empleado_Zonas_Viveros_Localización`, `Producto_Fecha de caducidad`, `Producto_Stock`, `Producto_Tipo`, `Producto_Precio`, `Producto_Codigo de barras`, `Producto_Zonas_Nombre`, `Producto_Zonas_Viveros_Nombre`, `Producto_Zonas_Viveros_Horario`, `Producto_Zonas_Viveros_Localización`, `Cliente_Fidelización`, `Cliente_DNI`, `Cliente_Nombre`),
  INDEX `fk_Pedido_Empleado1_idx` (`Empleado_CSS` ASC, `Empleado_Nombre` ASC, `Empleado_Seguridad Social` ASC, `Empleado_DNI` ASC, `Empleado_Nómina` ASC, `Empleado_Zonas_Nombre` ASC, `Empleado_Zonas_Viveros_Nombre` ASC, `Empleado_Zonas_Viveros_Horario` ASC, `Empleado_Zonas_Viveros_Localización` ASC) VISIBLE,
  INDEX `fk_Pedido_Producto1_idx` (`Producto_Fecha de caducidad` ASC, `Producto_Stock` ASC, `Producto_Tipo` ASC, `Producto_Precio` ASC, `Producto_Codigo de barras` ASC, `Producto_Zonas_Nombre` ASC, `Producto_Zonas_Viveros_Nombre` ASC, `Producto_Zonas_Viveros_Horario` ASC, `Producto_Zonas_Viveros_Localización` ASC) VISIBLE,
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_Fidelización` ASC, `Cliente_DNI` ASC, `Cliente_Nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Empleado1`
    FOREIGN KEY (`Empleado_CSS` , `Empleado_Nombre` , `Empleado_Seguridad Social` , `Empleado_DNI` , `Empleado_Nómina` , `Empleado_Zonas_Nombre` , `Empleado_Zonas_Viveros_Nombre` , `Empleado_Zonas_Viveros_Horario` , `Empleado_Zonas_Viveros_Localización`)
    REFERENCES `mydb`.`Empleado` (`CSS` , `Nombre` , `Seguridad Social` , `DNI` , `Nómina` , `Zonas_Nombre` , `Zonas_Viveros_Nombre` , `Zonas_Viveros_Horario` , `Zonas_Viveros_Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Producto1`
    FOREIGN KEY (`Producto_Fecha de caducidad` , `Producto_Stock` , `Producto_Tipo` , `Producto_Precio` , `Producto_Codigo de barras` , `Producto_Zonas_Nombre` , `Producto_Zonas_Viveros_Nombre` , `Producto_Zonas_Viveros_Horario` , `Producto_Zonas_Viveros_Localización`)
    REFERENCES `mydb`.`Producto` (`Fecha de caducidad` , `Stock` , `Tipo` , `Precio` , `Codigo de barras` , `Zonas_Nombre` , `Zonas_Viveros_Nombre` , `Zonas_Viveros_Horario` , `Zonas_Viveros_Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_Fidelización` , `Cliente_DNI` , `Cliente_Nombre`)
    REFERENCES `mydb`.`Cliente` (`Fidelización` , `DNI` , `Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
