-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 19:27:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Diagrama_Viveros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Diagrama_Viveros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Diagrama_Viveros` DEFAULT CHARACTER SET utf8 ;
USE `Diagrama_Viveros` ;

-- -----------------------------------------------------
-- Table `Diagrama_Viveros`.`Viveros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diagrama_Viveros`.`Viveros` (
  `Horario` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Localización`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diagrama_Viveros`.`Zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diagrama_Viveros`.`Zonas` (
  `Nombre` VARCHAR(10) NOT NULL,
  `Viveros_Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`, `Viveros_Localización`),
  INDEX `fk_Zonas_Viveros_idx` (`Viveros_Localización` ASC) VISIBLE,
  CONSTRAINT `fk_Zonas_Viveros`
    FOREIGN KEY (`Viveros_Localización`)
    REFERENCES `Diagrama_Viveros`.`Viveros` (`Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diagrama_Viveros`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diagrama_Viveros`.`Empleado` (
  `CSS` VARCHAR(10) NOT NULL,
  `Seguridad Social` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Nómina` INT NULL,
  `Zonas_Nombre` VARCHAR(10) NOT NULL,
  `Zonas_Viveros_Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CSS`, `Zonas_Nombre`, `Zonas_Viveros_Localización`),
  INDEX `fk_Empleado_Zonas1_idx` (`Zonas_Nombre` ASC, `Zonas_Viveros_Localización` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Zonas1`
    FOREIGN KEY (`Zonas_Nombre` , `Zonas_Viveros_Localización`)
    REFERENCES `Diagrama_Viveros`.`Zonas` (`Nombre` , `Viveros_Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diagrama_Viveros`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diagrama_Viveros`.`Cliente` (
  `DNI` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fidelización` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diagrama_Viveros`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diagrama_Viveros`.`Productos` (
  `Codigo de barras` VARCHAR(10) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Precio` VARCHAR(45) NOT NULL,
  `Stock` VARCHAR(45) NULL,
  `Fecha de caducidad` VARCHAR(45) NOT NULL,
  `Zonas_Nombre` VARCHAR(10) NOT NULL,
  `Zonas_Viveros_Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo de barras`, `Zonas_Nombre`, `Zonas_Viveros_Localización`),
  INDEX `fk_Productos_Zonas1_idx` (`Zonas_Nombre` ASC, `Zonas_Viveros_Localización` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Zonas1`
    FOREIGN KEY (`Zonas_Nombre` , `Zonas_Viveros_Localización`)
    REFERENCES `Diagrama_Viveros`.`Zonas` (`Nombre` , `Viveros_Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diagrama_Viveros`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diagrama_Viveros`.`Pedido` (
  `PedidoID` VARCHAR(10) NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  `Direccion de envio` VARCHAR(45) NOT NULL,
  `Importe` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Cliente_DNI` VARCHAR(10) NOT NULL,
  `Productos_Codigo de barras` VARCHAR(10) NOT NULL,
  `Productos_Zonas_Nombre` VARCHAR(10) NOT NULL,
  `Productos_Zonas_Viveros_Localización` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PedidoID`, `Cliente_DNI`, `Productos_Codigo de barras`, `Productos_Zonas_Nombre`, `Productos_Zonas_Viveros_Localización`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_DNI` ASC) VISIBLE,
  INDEX `fk_Pedido_Productos1_idx` (`Productos_Codigo de barras` ASC, `Productos_Zonas_Nombre` ASC, `Productos_Zonas_Viveros_Localización` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Empleado1`
    FOREIGN KEY ()
    REFERENCES `Diagrama_Viveros`.`Empleado` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_DNI`)
    REFERENCES `Diagrama_Viveros`.`Cliente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Productos1`
    FOREIGN KEY (`Productos_Codigo de barras` , `Productos_Zonas_Nombre` , `Productos_Zonas_Viveros_Localización`)
    REFERENCES `Diagrama_Viveros`.`Productos` (`Codigo de barras` , `Zonas_Nombre` , `Zonas_Viveros_Localización`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
